_target_: graspsampling.hands.URDFHand
file_name: grasp_gen/assets/xarm/xarm_gripper.urdf
grasp_frame: xarm_gripper_base_link
maximum_aperture: 0.0889236
approach_direction: [0., 0., 1.]
open_configurations:
  - [0.]
close_configurations:
  - [0.85]
width: 0.0889236
depth: 0.1621402
closing_regions:
  - extents: [0.09, 0.02, 0.05]
    translation: [0.0, 0.0, 0.1621402]
    rotation_wxyz: [1., 0., 0., 0.]
contact_points:
  - link_name: left_finger
    location: [0.0, 0.0444618, 0.1621402]
    normal: [0., -1., 0.]
  - link_name: right_finger
    location: [0.0, -0.0444618, 0.1621402]
    normal: [0., 1., 0.]
transform_offset_from_asset_to_graspgen_convention: [[0.0, 0.0, 0.0], [0.0, 0.0, -0.70710678, 0.70710678]] # expressed as translation and quaternion[[xyz],[xyzw]]
symmetric_antipodal: True
